FROM maven:3.8.4-openjdk-17
ENV SENHA_POSTGRESQL postgres

WORKDIR /app
WORKDIR /tmp

RUN git clone https://github.com/matheushajer/gerenciador-de-pedidos.git
WORKDIR /tmp/gerenciador-de-pedidos/entrega

RUN mvn clean package -DskipTests

# Copia o jar para o diretorio /app
RUN cp target/*.jar /app


# Expoe a porta 8081
EXPOSE 8081
WORKDIR /app

# Define o comando para iniciar a API
CMD java -jar $(ls | grep .jar)
